// <auto-generated />
using System;
using Festival.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Festival.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FestivalDbContext))]
    partial class FestivalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Festival.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("AssignmentId");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignmentRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FestivalDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("RowCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SpotCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SpotNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentRequestId", "AttendeeId")
                        .IsUnique();

                    b.HasIndex("FestivalDayId", "AttendeeId")
                        .IsUnique();

                    b.HasIndex("FestivalDayId", "SpotCode")
                        .IsUnique();

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("Festival.Domain.Attendees.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("AttendeeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("AttendeeCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Attendees", (string)null);
                });

            modelBuilder.Entity("Festival.Domain.FestivalDays.FestivalDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("FestivalDayId");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("FestivalDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_FestivalDays_AssignmentWindow_StartBeforeEnd", "\"AssignmentWindowStart\" < \"AssignmentWindowEnd\"");
                        });
                });

            modelBuilder.Entity("Festival.Domain.Spots.Spot", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("SpotCode");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("SpotNumber");

                    b.Property<string>("RowCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Code");

                    b.HasIndex("ZoneId", "RowCode", "Number")
                        .IsUnique();

                    b.ToTable("Spots", (string)null);
                });

            modelBuilder.Entity("Festival.Domain.Zones.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ZoneId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("Festival.Infrastructure.Persistence.Models.AssignmentRequestAttendeeRow", b =>
                {
                    b.Property<Guid>("AssignmentRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("AttendeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("AssignmentRequestId", "Position");

                    b.HasIndex("AssignmentRequestId", "AttendeeCode")
                        .IsUnique();

                    b.ToTable("AssignmentRequestAttendees", (string)null);
                });

            modelBuilder.Entity("Festival.Infrastructure.Persistence.Models.AssignmentRequestRow", b =>
                {
                    b.Property<Guid>("AssignmentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("AssignmentRequestId");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FestivalDayId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RejectionMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("AssignmentRequestId");

                    b.HasIndex("FestivalDayId", "RequestedAt");

                    b.ToTable("AssignmentRequests", (string)null);
                });

            modelBuilder.Entity("Festival.Domain.Assignments.Assignment", b =>
                {
                    b.HasOne("Festival.Infrastructure.Persistence.Models.AssignmentRequestRow", null)
                        .WithMany()
                        .HasForeignKey("AssignmentRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Festival.Domain.Attendees.Attendee", null)
                        .WithMany()
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Festival.Domain.FestivalDays.FestivalDay", null)
                        .WithMany()
                        .HasForeignKey("FestivalDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Festival.Domain.Spots.Spot", null)
                        .WithMany()
                        .HasForeignKey("SpotCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Festival.Domain.FestivalDays.FestivalDay", b =>
                {
                    b.OwnsOne("Festival.Domain.FestivalDays.AssignmentWindow", "AssignmentWindow", b1 =>
                        {
                            b1.Property<Guid>("FestivalDayId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time without time zone")
                                .HasColumnName("AssignmentWindowEnd");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone")
                                .HasColumnName("AssignmentWindowStart");

                            b1.HasKey("FestivalDayId");

                            b1.ToTable("FestivalDays");

                            b1.WithOwner()
                                .HasForeignKey("FestivalDayId");
                        });

                    b.Navigation("AssignmentWindow")
                        .IsRequired();
                });

            modelBuilder.Entity("Festival.Domain.Spots.Spot", b =>
                {
                    b.HasOne("Festival.Domain.Zones.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Festival.Infrastructure.Persistence.Models.AssignmentRequestAttendeeRow", b =>
                {
                    b.HasOne("Festival.Infrastructure.Persistence.Models.AssignmentRequestRow", "AssignmentRequest")
                        .WithMany("Attendees")
                        .HasForeignKey("AssignmentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignmentRequest");
                });

            modelBuilder.Entity("Festival.Infrastructure.Persistence.Models.AssignmentRequestRow", b =>
                {
                    b.HasOne("Festival.Domain.FestivalDays.FestivalDay", null)
                        .WithMany()
                        .HasForeignKey("FestivalDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Festival.Infrastructure.Persistence.Models.AssignmentRequestRow", b =>
                {
                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
